---
- hosts: ELK

  vars:
    usuario: root # Usuario
    password: $6$1/K.DtZ67H$o45NRNIGniy2krRS/YLGq68TkbTJn3aHLg83G4hZbn4hkMm/n.zy7/cO.PqANYg8IKxQQ8D.PsOfz3VjR4HIB1 # contraseña [Generada con: mkpasswd --method=SHA-512]

  tasks:

  - name: cambiar la contraseña de root
    user: name={{ usuario }} password="{{ password }}" update_password=always