---
# Gestionar LVM en LiNUX
- hosts: servidores

  vars:

    lvm_ope: ''          # Operación que se quiere realizar, los valores posibles son: 'crear', 'borrar' y 'extender'
    vgname: 'datos-vg'   # Nombre del VG
    disks: '/dev/sdb'    # Discos para el VG ('/dev/sdb,/dev/sdc,/dev/sdd,...' en el caso de una extensión hay que indicar todos los discos, no solo el que se añade)
    lvname: 'datos-lv'   # Nombre del LV
    mnt_point: '/datos'  # Punto de montaje para el LV
    lvsize: '100%FREE'   # Tamaño del LV ('10G' para un LV de 10 GB, '512' para uno de 512 MB)
    fs_type: 'ext4'      # Tipo del filesystem para el LV (ext3, ext4, xfs, ...)
    extend_opt: '-L+10G' # Opciones de lvextend ('-L+10G' para incrementar 10 GB el tamaño, '-l+100%FREE' para usar todo el espacio libre)

  tasks:

  - name: crear un VG
    lvg: vg={{ vgname }} pvs={{ disks }} state=present
    when: lvm_ope == 'crear'

  - name: crear un LV
    lvol: vg={{ vgname }} lv={{ lvname }} size={{ lvsize }} state=present
    when: lvm_ope == 'crear'

  - name: crear el filesystem
    filesystem: fstype={{ fs_type }} dev=/dev/{{ vgname }}/{{ lvname }}
    when: lvm_ope == 'crear'

  - name: montar el filesystem
    mount: name={{ mnt_point }} src=/dev/{{ vgname }}/{{ lvname }} fstype={{ fs_type }} state=mounted
    when: lvm_ope == 'crear'

  - name: extender un VG
    lvg: vg={{ vgname }} pvs={{ disks }}
    when: lvm_ope == 'extender'

  - name: extender LV
    command: lvextend {{ extend_opt }} /dev/{{ vgname }}/{{ lvname }}
    when: lvm_ope == 'extender'

  - name: cambiar el tamaño del filesystem
    command: resize2fs /dev/{{ vgname }}/{{ lvname }}
    when: lvm_ope == 'extender'

  - name: desmontar el filesystem
    mount: name={{ mnt_point }} src=/dev/{{ vgname }}/{{ lvname }} fstype={{ fs_type }} state=absent
    when: lvm_ope == 'borrar'

  - name: eliminar un LV
    lvol: vg={{ vgname }} lv={{ lvname }} size={{ lvsize }} state=absent force=yes
    when: lvm_ope == 'borrar'

  - name: eliminar un VG
    lvg: vg={{ vgname }} pvs={{ disks }} state=absent force=yes
    when: lvm_ope == 'borrar'